### ISSUE TITLE
How to trigger BB PR builds

### ISSUE THREAD

**Issue by dantran** [Eernie/bitbucket-webhooks-plugin#72]
With the latest upgrade from this plugin and Jenkins BB branch source plugin, my Jenkins BB branch source team job no longer triggers any PR build for any repo.

My goal is to configure 

  * All 'release' branches to show up ( master and release/*)
  * PR builds for any dev branch  ( outside of master and release)

My apology for posting this question here, since I am not able to get attention at Jenkins user list :-)

Very appreciated any help

**Comment by casz** [comment]
what version of bitbucket are you using?

**Comment by dantran** [comment]
we are using v4.10.1.   I have tried the scan many times. We currently have about 5 teams projects

**Comment by casz** [comment]
I think it's something in the latest Jenkins plugin release, I see the events in the event log... But they are not getting processed correctly

**Comment by casz** [comment]
![image](https://user-images.githubusercontent.com/1661688/32067912-07d60c9c-ba85-11e7-829e-dcf0521d4bd1.png)
Lots of created events but no removed events till I hit "Scan"

**Comment by dantran** [comment]
@Joseph Petersen   you also not seeing PR at your side?

**Comment by casz** [comment]
@dantran Indeed and I believe it's the latest Jenkins plugin... going to revert and see if it helps.

**Comment by dantran** [comment]
very glad it is reproducible. What are versions of your BB and Jenkins BB branch source?

**Comment by stephenc** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/76

**Comment by casz** [comment]
fixed in cloudbees-bitbucket-branch-source-2.2.5

**Comment by dantran** [comment]
with the latest update from BB Jenkins branch source plugin, I still don't see the PR builds showing up

here is a partial event log

  30 branches were processed
Looking up msm/msm for pull requests
Checking PR-482 from MSM/msm and branch bugfix/jar-signing
Checking PR-479 from MSM/msm and branch release/dpc-1.0.2
Checking PR-454 from MSM/msm and branch feature/dockerfile-to-install-dpc-in-docker-to-test
Checking PR-417 from MSM/msm and branch bugfix/287295
Checking PR-413 from MSM/msm and branch feature/SonarQube

  5 pull requests were processed
[Sun Nov 05 10:27:40 PST 2017] com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$1 CREATED event from 10.199.240.28 ⇒ https://xxxxxxx/bitbucket-scmsource-hook/notify with timestamp Sun Nov 05 10:27:10 PST 2017 processed in 30 sec

Thoughts?

**Comment by casz** [comment]
@dantran did you restart Jenkins after updating the plugin?

**Comment by dantran** [comment]
Yes, we always restart out Jenkins after update plugins

I also trying to open PR, decline,  and open again.  I do see CREATE, REMOVE, and UPDATE events

**Comment by dantran** [comment]
my configurations:
 
Discover branches: all branches

Discover pull requests from origin: both

Filter by name (with wildcards) include: master bugfix/* feature/* release/*

**Comment by stephenc** [comment]
You’ll want to add `PR-*` to your filter by name (it’s filtering heads by head name, and PRs have a SCMHead starting with PR)

**Comment by dantran** [comment]
@stephenc it works, i ended up with

    master bugfix/* feature/* release/* PR-*-merge

otherwise, I will have 2 PR jobs PR.

Then optimized further with 

    master release/* PR-*-merge

Thanks for helping out

**Comment by stephenc** [comment]
Way are you doing:

> Discover pull requests from origin: both

If you only want the merge one?

**Comment by dantran** [comment]
@stephenc your suggestion is much more concise
I now have

Discover pull requests from origin: 
    merging xxxxx

Filter by name (with wildcards) include: 
    master  release/* PR-*

**Comment by stephenc** [comment]
You may want to try https://wiki.jenkins.io/display/JENKINS/SCM+Branch+PR+Filter+Plugin for filtering instead, that way you could limit to PRs targeting only master and release

**Comment by dantran** [comment]
@stephenc the specialized add-on plugin is even better. Thanks
